defaults:
  - _self_

wandb:
  entity: "tylerlum"
  project: "NeRF_Grasp_Metric_V2"
  name: ${datetime_str:}
  group: ""
  job_type: ""

data:
  frac_val: 0.1
  frac_test: 0.1
  frac_train: ${eval:1 - ${data.frac_val} - ${data.frac_test}}
  # input_dataset_root_dir: "graspdata_learned_metric_dataset"
  # input_dataset_path: "2023-08-18_13-27-27_learned_metric_dataset.h5"  Medium with 30k
  input_dataset_root_dir: "2023-08-25_evaled_grasp_config_dicts_learned_metric_dataset"
  input_dataset_path: "2023-08-26_02-23-51_learned_metric_dataset.h5"

  max_num_data_points: ${eval:None}

dataloader:
  batch_size: 64
  num_workers: 8
  pin_memory: True
  load_nerf_grid_inputs_in_ram: False
  load_grasp_successes_in_ram: False
  load_grasp_transforms_in_ram: False
  load_nerf_configs_in_ram: False

training:
  grad_clip_val: 1.0
  lr: 1e-4
  weight_decay: 1e-3
  betas: [0.9, 0.999]
  label_smoothing: 0.0
  lr_scheduler_name: "constant"
  lr_scheduler_num_warmup_steps: 0
  n_epochs: 1000
  val_freq: 5
  val_on_epoch_0: False
  save_checkpoint_freq: 5
  save_checkpoint_on_epoch_0: False

checkpoint_workspace:
  root_dir: "Train_DexGraspNet_NeRF_Grasp_Metric_workspaces"
  leaf_dir: ${datetime_str:}
  force_no_resume: True

random_seed: 42
dry_run: False
